version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7
      - image: circleci/postgres:9.6-alpine
      - image: circleci/mongo:3.6-ram

    working_directory: ~/repo

    environment:
      MONGODB_URI: mongodb://localhost/testing
      SQL_URI: postgresql://postgres@localhost/testing

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            pip install -r requirements.txt
            mkdir -p test-reports

      - save_cache:
          paths:
            - ~/venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Wait for SQL
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Run Tests
          command: |
            . ~/venv/bin/activate
            nosetests --verbose --with-xunit --xunit-file=test-reports/nosetests.xml

      - run:
          name: Run Linter
          command: |
            . ~/venv/bin/activate
            flake8

      - store_artifacts:
          path: test-reports

      - store_test_results:
          path: test-reports
workflows:
  version: 2
  test-and-build:
    jobs:
      - test
